language: go

go:
- 1.11.x

git:
  depth: 3

#install: true

dist: trusty
sudo: false

os:
- windows

notifications:
  email: false

install:
- travis_wait env GO111MODULE=on go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
- travis_wait env GO111MODULE=on go get -u

script:
- travis_wait env GO111MODULE=on goversioninfo -64
- travis_wait env GO111MODULE=on go build -ldflags "-X main.version=`echo $TRAVIS_TAG | sed -r 's/[vV]?([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2.\3/'`"
- travis_wait env GO111MODULE=on go test -v -race ./...

before_deploy:
#- tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz cord.stool.exe
- 7z ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip cord.stool.exe

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: cY55nm6y+4C22dM6Si6e6soNTJStXax/DC8hRbmgi2KsZaxktqcQT1cxWD8wTR5P16JXFngHjMprK6mrQHGjz4B7JQFLmNmoGiE4QmiB0IRKeng3O/ViMhxJT/RpOPJCm0S9o94Z8iXLGoeBrd4auruaJ4LJ4qC+Ath6SVexbKJc+Ln0HYXDHvZvMANdR/GUHnbgqooZZieLsXbPngnM/mtLK7HRfQv1yRuYBmXLB9wyWMW3mWuttHrOPgojxdBlJlEahNdUP2iYg5/F+uAC8z1Rydh5F3r4LFkqK5uE0akrT2bHzPZ7OYBYhePQf/n/woFwBsfKsXhu714txgPPrKyJKzjKjw/F1S1nxNw6eSxl+lm1Ww4Wez8hbUUtaMpc7eDzV3/cEF+ajscU7GgeJRqAcTun0GsIjPttwF7fQI+izzbtcTpf9b9q1ExbUa+C6CsUl3yD/OhTYTWi84DO1UDhtO5Q0tcQ45797/evZFPIEwrBYtZoE+bdNCAU+ne68+vrj6BR3r24T5/p9IGRJGx6ABP1fmHEmBlw/M6n5COQoN8E1fsn1/fZ6Cwycg3IDRumGQVDuy1kM/zrabFGFybiZXugn6uMSqgf60fCEYezNSIbAV58X0PKgf6o7jO6nVTzO6a9GhyxU5nOD3kH4zpcMolHqoYiBKbOngYrRAs=
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip
  on:
    tags: true
    repo: ProtocolONE/cord.stool
